function createsurf(xdata1, ydata1, zdata1, Parent1)
%CREATESURF(xdata1, ydata1, zdata1, Parent1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  PARENT1:  surf parent

%  Auto-generated by MATLAB on 08-Mar-2020 00:14:35

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',Parent1,'FaceColor','Jet',...
    'EdgeColor','none');

